# targets:
#   $default:
#     builders:
#       redux_gen|redux_gen_annotation:
#         enabled: true

builders:
  redux_gen:
    import: "package:redux_gen/builder.dart"
    builder_factories: ["epicConfigGeneration"]
    build_extensions: { ".dart": [".epic_config.dart"] }
    auto_apply: dependents
    build_to: source

  # redux_gen:
  #   target: ":redux_gen"
  #   import: "package:redux_gen/builder.dart"
  #   builder_factories: ["reduxGenAnnotation"]
  #   build_extensions: { ".dart": [".redux_gen.g.part"] }
  #   auto_apply: dependents
  #   build_to: source
  #   applies_builders: ["source_gen|combining_builder"]
