name: redux_gen
description: A new Flutter package project.
version: 0.0.1
author: Yura Shevelev <sirhikshevelev@gmail.com>
homepage: https://github.com/WhiteshadowYS/redux_gen.git

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  build: '>=0.12.0 <2.0.0'  
  source_gen: ^0.9.10+1
  redux_gen_annotation:
    git:
      url: git://github.com/WhiteshadowYS/redux_gen_annotation.git
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_test: ^0.10.0  
  build_runner: ^1.10.11 
  test: ^1.0.0

flutter:

