name: redux_gen
description: A new Flutter package project.
version: 0.0.1
author: Yura Shevelev <sirhikshevelev@gmail.com>
homepage: https://github.com/WhiteshadowYS/redux_gen.git

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

